# Generated by Django 3.2.6 on 2022-01-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.TextField(default='', max_length=300)),
                ('quanity', models.TextField(default='', max_length=300)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
