# Generated by Django 3.2.6 on 2022-01-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='quanity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
    ]
