# Generated by Django 3.2.6 on 2022-01-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220119_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
