# Generated by Django 3.2.6 on 2022-01-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
    ]
