# Generated by Django 3.2.6 on 2022-01-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_store_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Product',
        ),
    ]
