# Generated by Django 4.0.2 on 2022-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='remindTime',
        ),
        migrations.AddField(
            model_name='notification',
            name='schedule_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
