# Generated by Django 4.0.2 on 2022-03-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_notification_remindtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='schedule_id',
        ),
    ]
